### ISSUE TITLE
shpool not setting kernel window size struct completely

### ISSUE THREAD

**Issue by willangley** [shell-pool/shpool#13]
I noticed a panic with a kitty terminal mouse interaction running under `shpool`, and reported it as a kitty bug (kovidgoyal/kitty#7405). kitty's author investigated, and said:

> This is a bug in shpool it is not setting the full window size struct
> (the latter two pixel size fields to be precise) to the kernel via
> TIOCWINSZ for tty's it creates.
> 
> That said, I will fix the kitten to at least not panic, though mouse
> interactions will not work.

_Originally posted by @kovidgoyal in https://github.com/kovidgoyal/kitty/issues/7405#issuecomment-2087946713_

Can you update shpool to do this?

**Comment by ethanpailes** [comment]
Thanks for the report, I'll look into fixing this.

**Comment by ethanpailes** [comment]
@willangley I just merged a fix. You can see if it works out for you by building shpool from source

**Comment by ethanpailes** [comment]
I went through the reproduction steps with the patch applied and it no longer crashes kitty 0.32.1-1 (the version of the debian package I got kitty from)
