### ISSUE TITLE
non-zero exit status upon `shpool detach`

### ISSUE THREAD

**Issue by rlue** [shell-pool/shpool#130]
### What happened

```sh
$ shpool attach main
shpool:main $ shpool detach
$ echo $?
1
```

### What I expected to happen

I expect `shpool` to exit 0 when explicitly detaching from a session. This makes the following auto-attach setup smoother:

```
# ~/.ssh/authorized_keys
command="XDG_RUNTIME_DIR=/run/user/1000 $HOME/.cargo/bin/shpool attach main || bash" ssh-rsa AAAAB3N...
```

(In this setup, I would like `shpool detach` to drop me out of the SSH session entirely, but it falls through to a new bash prompt instead.)

### Version info

0.6.3

### Logs

N/A? (happy to add them if you aren't getting the same result for some reason.)

**Comment by ethanpailes** [comment]
This seems like a reasonable ask, though I want to check to code to see if we have a good reason for doing it like this before changing it.

**Comment by ethanpailes** [comment]
Wound up being pretty easy. We can just switch some ClientConnectionMsg::Disconnect messages to DisconnectExit(0). I have a patch locally, but I need to write tests and button it up a bit.
