### ISSUE TITLE
Is shtool detach from a running session possible?

### ISSUE THREAD

**Issue by pmorch** [shell-pool/shpool#146]
**What happened**
Lets say I've run a long-running app in a running session and want to detach and do something else in that terminal.

What I *can* do: run `shpool detach mysession` from another session

What I'd like to do: Somehow detach the currrent terminal, without hitting `^C` to kill the running app.

Is that possible?

In `tmux` it is `CTRL+B d`. Yes I know, this is not `tmux`. What I **love** about `shpool` is that my scrolling and mouse etc work exactly like a normal terminal. `CTRL+B d` is the only thing from `tmux` that I miss.

```shell
$ shpool version
shpool 0.7.0 ($internalCorpVersion)
```

**Comment by ethanpailes** [comment]
We got you covered :)

https://github.com/shell-pool/shpool/blob/master/CONFIG.md#detach-keybinding

This should probably be mentioned in the README as well though.

**Comment by pmorch** [comment]
This was added to the README in commit 62af231.

**Comment by ethanpailes** [comment]
Thanks! I should have linked this issue in that patch.
