### ISSUE TITLE
sourcing ~/.bashrc clobbers the shpool prompt prefix

### ISSUE THREAD

**Issue by ethanpailes** [shell-pool/shpool#35]
Currently if you make some tweak to your shell's .rc files in which you have a custom prompt configured, then reload the changes by doing `source ~/.bashrc` or `. ~/.bashrc`, shpool's prompt prefix that it injects on startup will get clobbered. This is a bit sad.

I can think of a few approaches to this, none of which are entirely seemless:

1. Add a new `shpool prompt-hook <bash|zsh|fish>` subcommand that is meant to be invoked with `$(shpool prompt-hook bash)`, which you can add at the end of your `.bashrc`. In addition to doing the usual thing to inject a prompt, it sets a SHPOOL_PROMPT_ALREADY_SET_UP=true env var, which the normal prompt hooks setup code checks for in order to avoid double-adding the prompt on first startup.
2. Add a new keybinding so that users can have shpool re-inject the prompt after they have sourced their config

The trouble with both of these approaches is that they are too manual. Shpool is meant to be an easy option that works well out of the box without configuration. We could have skipped all the prompt hook stuff if we were willing to demand that users edit their .rc files in order to use shpool, since they can just incorperate it into their normal prompt config, but shpool is meant to be easy to use even for people who are not comfortable with stuff like that.

**Comment by mrzv** [comment]
Closely related to this issue is the ability to disable automatic prompt setting in the config. I would like to be able to disable it and add `$SHPOOL_SESSION_NAME` to the prompt on my own.

**Comment by ethanpailes** [comment]
You can do that by setting `prompt_prefix = ""` in the config. We should probably do a better job of documenting that.

**Comment by mrzv** [comment]
Brilliant. Thanks!

**Comment by mrzv** [comment]
Except that didn't work. Am I supposed to put it in some section?

**Comment by mrzv** [comment]
Yup, that did it. Many thanks. It's a fantastic tool you've written. More feature requests are on the way. ;-)

**Comment by ethanpailes** [comment]
I just made https://github.com/shell-pool/shpool/pull/39 in order to try to document the config options better

**Comment by ethanpailes** [comment]
On thinking about this more, I think any fix is going to be more complex than is worth it. There is already a decent workaround in just disabling the prompt and configuring prompt setup yourself, and any fix will require manual intervention anyway so it is a bit of a lost cause from a "just working" perspective.
