### ISSUE TITLE
Preserve environment variables

### ISSUE THREAD

**Issue by mrzv** [shell-pool/shpool#38]
**What happened**
Right now, when `shpool` launches a new shell for the session, it doesn't preserve environment variables. This loses some useful information, for example, whether I'm running via SSH, which I test by checking if `$SSH_CLIENT` is defined.

**What I expected to happen**
Preserve the environment variables from the shell that launched us.

**Version info**
`shpool 0.6.1`

**Comment by ethanpailes** [comment]
Does [forward_env](https://github.com/shell-pool/shpool/blob/a22faf05f9d32a802965cc84797bbc3b8539ed65/libshpool/src/config.rs#L173) do what you want?

If you want to foward all environment variables, there is currently no way to do that, but you can configure a subset.

**Comment by mrzv** [comment]
That worked for `$SSH_CLIENT`. Thanks!

**Comment by ethanpailes** [comment]
You want me to close this or do you think a more general "forward everything" option would be useful?

**Comment by mrzv** [comment]
You can close it. I don't have a strong opinion on the general "forward everything". At least, not yet.

**Comment by ethanpailes** [comment]
Sounds good, we'll KISS for now then
