### ISSUE TITLE
"Detach" action in README

### ISSUE THREAD

**Issue by samgriesemer** [shell-pool/shpool#45]
Minor detail from the README, but when setting up my config file with the block

```
[[keybinding]]
binding = "Ctrl-a d"
action = "Detach"
```

`shpool` complains about the action name after restarting:

```
unknown variant `Detach`, expected `detach` or `noop`
```

This should presumably just be updated to `action = "detach"` for those of us just copy-pasting this into a new config file.

**Comment by ethanpailes** [comment]
Oh, thanks for catching this. This is a holdover from before I was lowercasing enum identifiers in the config parsing.

**Comment by ethanpailes** [comment]
I'm bundling the fix into https://github.com/shell-pool/shpool/pull/39

**Comment by thiswillbeyourgithub** [comment]
Stumbled upon this one too. The lack of error message when trying to attach is an issue. I had to peek through the logs to figure it out
