### ISSUE TITLE
Unable to install with cargo on Debian Bookworm

### ISSUE THREAD

**Issue by GitPuffy** [shell-pool/shpool#50]
**What happened**
Following the installation instructions I received many "package `<name>`cannot be built because it requires `<name/version>` or newer, while the currently active `<name/version>` is ..." error messages

**What I expected to happen**
Expected shpool to be installed

**To Reproduce**
1. cargo install shpool

**Version info**
OS: Debian Bookworm
Linux `<hostname>` 6.6.31+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64 GNU/Linux

**Logs**
Unknown / not installed yet

**Comment by ethanpailes** [comment]
Have you installed cargo via your package manager or via [rustup](https://rustup.rs/)? shpool's MSRV is 1.74, which is fairly new and a lot of distros aren't there yet (my debian flavored distro is currently only at rustc 1.70).

**Comment by GitPuffy** [comment]
I used the Debian distro of cargo.  I will look into removing it and installing cargo from rustup.

**Comment by ethanpailes** [comment]
Ok. I'll close this for now, but this is on my radar. My plan is to just hold the line on the MSRV until it is building on more distros. At the least, shpool should build on Debian Testing without having to resort to rustup. Currently, my Arch box is on rustic 1.78 already so at least arch can build shpool fine, but my guess is most distros are not that bleeding edge.
