### ISSUE TITLE
automate releases

### ISSUE THREAD

**Issue by kai-tub** [shell-pool/shpool#53]
Hey,

the tool looks quite interesting!
It would be neat if you could add pre-build binaries to the releases, maybe something [similar to the workflow in lan-mouse](https://github.com/feschber/lan-mouse/blob/main/.github/workflows/tagged-release.yml) to automatically create it from a GitHub workflow.
Especially on some older servers with no privileges, it is sometimes not that easy to install the rust toolchain. ;)

Just my 5cts!

Thanks for working on the project!

**Comment by ethanpailes** [comment]
Oh yeah this seems like a good idea. Thanks for linking an example, that will make things easier!
